from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QButtonGroup


class Ui_Dialog(object):
    def setupUi(self, Dialog, fruit_info: dict):
        Dialog.setObjectName("Dialog")
        Dialog.resize(772, 577)

        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        Dialog.setFont(font)

        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setGeometry(QtCore.QRect(630, 510, 111, 41))
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("pushButton_2")

        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.apply_button = QtWidgets.QPushButton(Dialog)
        self.apply_button.setGeometry(QtCore.QRect(510, 510, 111, 41))
        self.apply_button.setFont(font)
        self.apply_button.setObjectName("pushButton_3")

        label_font = QtGui.QFont()
        label_font.setFamily("楷体")
        label_font.setPointSize(16)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 90, 72, 41))
        self.label.setFont(label_font)
        self.label.setObjectName("label")

        self.dlabel = QtWidgets.QLabel(Dialog)
        self.dlabel.setGeometry(QtCore.QRect(150, 30, 72, 31))
        self.dlabel.setFont(label_font)
        self.dlabel.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 160, 72, 41))
        self.label_3.setFont(label_font)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 91, 41))
        self.label_4.setFont(label_font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(50, 300, 61, 41))
        self.label_5.setFont(label_font)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 370, 61, 41))
        self.label_6.setFont(label_font)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(50, 440, 61, 41))
        self.label_7.setFont(label_font)
        self.label_7.setObjectName("label_7")

        self.splabel = QtWidgets.QLabel(Dialog)
        self.splabel.setGeometry(QtCore.QRect(270, 30, 72, 31))
        self.splabel.setFont(label_font)
        self.splabel.setObjectName("label_8")

        self.ulabel = QtWidgets.QLabel(Dialog)
        self.ulabel.setGeometry(QtCore.QRect(550, 30, 72, 31))
        self.ulabel.setFont(label_font)
        self.ulabel.setObjectName("label_9")

        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(390, 100, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(500, 100, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(630, 100, 115, 21))
        self.radioButton_3.setObjectName("radioButton_3")

        self.apple_group = QButtonGroup(self)
        self.apple_group.addButton(self.radioButton, 0)
        self.apple_group.addButton(self.radioButton_2, 1)
        self.apple_group.addButton(self.radioButton_3, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.apple_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.apple_discount.setGeometry(QtCore.QRect(140, 90, 81, 41))
        self.apple_discount.setFont(font)
        self.apple_discount.setObjectName("doubleSpinBox")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.apple_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.apple_price_text.setGeometry(QtCore.QRect(260, 90, 81, 41))
        self.apple_price_text.setFont(font)
        self.apple_price_text.setObjectName("plainTextEdit")


        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(390, 170, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(500, 170, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_6.setGeometry(QtCore.QRect(630, 170, 115, 21))
        self.radioButton_6.setObjectName("radioButton_6")

        self.banana_group = QButtonGroup(self)
        self.banana_group.addButton(self.radioButton_4, 0)
        self.banana_group.addButton(self.radioButton_5, 1)
        self.banana_group.addButton(self.radioButton_6, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.banana_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.banana_discount.setGeometry(QtCore.QRect(140, 160, 81, 41))
        self.banana_discount.setFont(font)
        self.banana_discount.setObjectName("doubleSpinBox_2")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.banana_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.banana_price_text.setGeometry(QtCore.QRect(260, 160, 81, 41))
        self.banana_price_text.setFont(font)
        self.banana_price_text.setObjectName("plainTextEdit_2")

        self.radioButton_7 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_7.setGeometry(QtCore.QRect(390, 240, 115, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_8.setGeometry(QtCore.QRect(500, 240, 115, 21))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_9.setGeometry(QtCore.QRect(630, 240, 115, 19))
        self.radioButton_9.setObjectName("radioButton_9")

        self.guava_group = QButtonGroup(self)
        self.guava_group.addButton(self.radioButton_7, 0)
        self.guava_group.addButton(self.radioButton_8, 1)
        self.guava_group.addButton(self.radioButton_9, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.guava_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.guava_discount.setGeometry(QtCore.QRect(140, 230, 81, 41))
        self.guava_discount.setFont(font)
        self.guava_discount.setObjectName("doubleSpinBox_3")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.guava_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.guava_price_text.setGeometry(QtCore.QRect(260, 230, 81, 41))
        self.guava_price_text.setFont(font)
        self.guava_price_text.setObjectName("plainTextEdit_3")

        self.radioButton_10 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_10.setGeometry(QtCore.QRect(390, 310, 115, 19))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_11.setGeometry(QtCore.QRect(500, 310, 115, 21))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_12.setGeometry(QtCore.QRect(630, 310, 115, 19))
        self.radioButton_12.setObjectName("radioButton_12")

        self.lime_group = QButtonGroup(self)
        self.lime_group.addButton(self.radioButton_10, 0)
        self.lime_group.addButton(self.radioButton_11, 1)
        self.lime_group.addButton(self.radioButton_12, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.lime_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.lime_discount.setGeometry(QtCore.QRect(140, 300, 81, 41))
        self.lime_discount.setFont(font)
        self.lime_discount.setObjectName("doubleSpinBox_4")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.lime_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.lime_price_text.setGeometry(QtCore.QRect(260, 300, 81, 41))
        self.lime_price_text.setFont(font)
        self.lime_price_text.setObjectName("plainTextEdit_4")

        self.radioButton_13 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_13.setGeometry(QtCore.QRect(390, 380, 115, 19))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_14.setGeometry(QtCore.QRect(500, 380, 115, 21))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_15.setGeometry(QtCore.QRect(630, 380, 115, 19))
        self.radioButton_15.setObjectName("radioButton_15")

        self.orange_group = QButtonGroup(self)
        self.orange_group.addButton(self.radioButton_13, 0)
        self.orange_group.addButton(self.radioButton_14, 1)
        self.orange_group.addButton(self.radioButton_15, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.orange_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.orange_discount.setGeometry(QtCore.QRect(140, 370, 81, 41))
        self.orange_discount.setFont(font)
        self.orange_discount.setObjectName("doubleSpinBox_5")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.orange_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.orange_price_text.setGeometry(QtCore.QRect(260, 370, 81, 41))
        self.orange_price_text.setFont(font)
        self.orange_price_text.setObjectName("plainTextEdit_5")


        self.radioButton_16 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_16.setGeometry(QtCore.QRect(390, 450, 115, 21))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_17.setGeometry(QtCore.QRect(500, 450, 115, 19))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_18.setGeometry(QtCore.QRect(630, 450, 115, 19))
        self.radioButton_18.setObjectName("radioButton_18")

        self.pomegranate_group = QButtonGroup(self)
        self.pomegranate_group.addButton(self.radioButton_16, 0)
        self.pomegranate_group.addButton(self.radioButton_17, 1)
        self.pomegranate_group.addButton(self.radioButton_18, 2)

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pomegranate_discount = QtWidgets.QDoubleSpinBox(Dialog)
        self.pomegranate_discount.setGeometry(QtCore.QRect(140, 440, 81, 41))
        self.pomegranate_discount.setFont(font)
        self.pomegranate_discount.setObjectName("doubleSpinBox_6")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pomegranate_price_text = QtWidgets.QPlainTextEdit(Dialog)
        self.pomegranate_price_text.setGeometry(QtCore.QRect(260, 440, 81, 41))
        self.pomegranate_price_text.setFont(font)
        self.pomegranate_price_text.setObjectName("plainTextEdit_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.button_groups = [self.apple_group, self.banana_group, self.guava_group,
                              self.lime_group, self.orange_group, self.pomegranate_group]
        self.discount_boxes = [self.apple_discount, self.banana_discount, self.guava_discount,
                               self.lime_discount, self.orange_discount, self.pomegranate_discount]
        self.fruit_price_text = [self.apple_price_text, self.banana_price_text, self.guava_price_text,
                                 self.lime_price_text, self.orange_price_text, self.pomegranate_price_text]
        self.fruit_list = fruit_info['fruits_list']

        for i in range(len(self.fruit_list)):
            self.fruit_price_text[i].setPlainText(str(fruit_info['fruits_price'][self.fruit_list[i]]))
            self.button_groups[i].button(fruit_info['fruits_unit'][self.fruit_list[i]]).setChecked(True)
            self.discount_boxes[i].setValue(fruit_info['fruits_discount'][self.fruit_list[i]])
            self.discount_boxes[i].setRange(0.00, 1.00)
            self.discount_boxes[i].setSingleStep(0.01)

        self.cancel_button.clicked.connect(self.close_window)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancel_button.setText(_translate("Dialog", "取消"))
        self.apply_button.setText(_translate("Dialog", "确定"))
        self.label.setText(_translate("Dialog", "苹果"))
        self.dlabel.setText(_translate("Dialog", "折扣"))
        self.label_3.setText(_translate("Dialog", "香蕉"))
        self.label_4.setText(_translate("Dialog", "番石榴"))
        self.label_5.setText(_translate("Dialog", "柠檬"))
        self.label_6.setText(_translate("Dialog", "橙子"))
        self.label_7.setText(_translate("Dialog", "石榴"))
        self.splabel.setText(_translate("Dialog", "单价"))
        self.ulabel.setText(_translate("Dialog", "单位"))

        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.radioButton.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_2.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_3.setText(_translate("Dialog", "RadioButton"))
        self.radioButton.setText("元/斤")
        self.radioButton.setFont(font)
        self.radioButton_2.setText("元/千克")
        self.radioButton_2.setFont(font)
        self.radioButton_3.setText("元/个")
        self.radioButton_3.setFont(font)
        self.apple_price_text.setPlainText(_translate("Dialog", "1.00"))

        self.radioButton_4.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_5.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_6.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_4.setText("元/斤")
        self.radioButton_4.setFont(font)
        self.radioButton_5.setText("元/千克")
        self.radioButton_5.setFont(font)
        self.radioButton_6.setText("元/个")
        self.radioButton_6.setFont(font)
        self.banana_price_text.setPlainText(_translate("Dialog", "2.00"))

        self.radioButton_7.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_8.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_9.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_7.setText("元/斤")
        self.radioButton_7.setFont(font)
        self.radioButton_8.setText("元/千克")
        self.radioButton_8.setFont(font)
        self.radioButton_9.setText("元/个")
        self.radioButton_9.setFont(font)
        self.guava_price_text.setPlainText(_translate("Dialog", "3.00"))

        self.radioButton_10.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_11.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_12.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_10.setText("元/斤")
        self.radioButton_10.setFont(font)
        self.radioButton_11.setText("元/千克")
        self.radioButton_11.setFont(font)
        self.radioButton_12.setText("元/个")
        self.radioButton_12.setFont(font)
        self.lime_price_text.setPlainText(_translate("Dialog", "4.00"))

        self.radioButton_13.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_14.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_15.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_13.setText("元/斤")
        self.radioButton_13.setFont(font)
        self.radioButton_14.setText("元/千克")
        self.radioButton_14.setFont(font)
        self.radioButton_15.setText("元/个")
        self.radioButton_15.setFont(font)
        self.orange_price_text.setPlainText(_translate("Dialog", "5.00"))

        self.radioButton_16.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_17.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_18.setText(_translate("Dialog", "RadioButton"))
        self.radioButton_16.setText("元/斤")
        self.radioButton_16.setFont(font)
        self.radioButton_17.setText("元/千克")
        self.radioButton_17.setFont(font)
        self.radioButton_18.setText("元/个")
        self.radioButton_18.setFont(font)
        self.pomegranate_price_text.setPlainText(_translate("Dialog", "6.00"))

    def close_window(self):
        self.close()


class Fruit_Settings_Window(QtWidgets.QDialog, Ui_Dialog):
    def __init__(self, fruit_info: dict):
        super().__init__()
        self.setupUi(self, fruit_info)

    def show_fruit_settings_window(self):
        self.show()
        self.exec_()
